### ISSUE TITLE
Python crash with macOS Catalina 10.15

### ISSUE THREAD

**Issue by notFloran** [TheGrowingPlant/mac-playbook#53]
https://stackoverflow.com/questions/58272830/python-crashing-on-macos-10-15-beta-19a582a-with-usr-lib-libcrypto-dylib

https://someguys.blog/2019-10-09-python-abort-on-macos-catalina/

**Comment by notFloran** [comment]
Issue is back:

```
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-darwin.so
  Reason: image not found
```
See https://gist.github.com/llbbl/c54f44d028d014514d5d837f64e60bac
